version: "3.8"

services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    links:
      - user-service
    depends_on:
      - user-service
    networks:
      - microservice-network
  user-service:
    build:
      context: ./user/
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3000:3000"
    volumes:
      - ./user:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - microservice-network
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    container_name: db
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  data:
    driver: local
